services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: gamedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gamedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8082"
      - "5005:5005"
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local